### PR TITLE
Modified to built on Linux and macOS

### PR DESCRIPTION
**Pull request by MKesenheimer**
Modified the code to built on Linux and macOS.
This should fix various errors (see Various Compilation Errors on Linux Debian #14).

### CODE REVIEW

**Comment by sysprogs** [comment]
Sorry, not sure why you did it, but your patch disables a few FLASH drivers and breaks the printing of the libusb commit ID.
We would love to merge your pull request, however we would kindly ask you to ensure it doesn't break or disable any existing functionality.

Also, we indeed used Windows-specific error codes (e.g. ERROR_INSUFFICIENT_BUFFER) in the commands we added. However, hardcoding these values in log.h would break any Windows-specific code that uses them to analyze values returned by the Win32 API functions. A better cross-platform way to do it would be to instead use the error codes that are defined in the log.h file already (e.g. ERROR_BUF_TOO_SMALL).

**Comment by MKesenheimer** [comment]
I mentioned in issue #14 that this pull request should more be seen as a guide where to fix certain errors. It was not meant to merge it directly without modifying it. I am no expert with this project and I suspect that you have better insights.

Please see issue #14 for more details.

On why I deleted the FLASH drivers: Obviously you did something different to the original project when implementing the code for the new drivers. The original project compiles just fine. However, if I compile your code, my linker can not find the newly defined symbols. Maybe you should check where the differences to the original project are.

And the code for displaying the libusb commit ID can simply not be correct:
```
LOG_OUTPUT("libusb1 " LIBUSB1_COMMIT "\n");
```
How should that work? This is not proper C++ code. There is at least string concatenation or whatever needed here. I can not imagine how this builds on Windows...

**Comment by sysprogs** [comment]
Thanks for your feedback. We maintain this OpenOCD fork in order to provide prebuilt OpenOCD packages for VisualGDB users. As VisualGDB only runs on Windows, we only build and test it on Windows as well.

If anyone is willing to submit a pull request resolving the Linux build issues without breaking anything, we won't mind merging it, but we won't do any Linux porting or testing on our side unless our VisualGDB workflow starts depending on it, sorry. 

Most Linux distros come with a pre-built OpenOCD package (and you can build the original version with autoconf), so there is overall very little benefit from porting this particular fork on Linux.

**Comment by MKesenheimer** [comment]
Fair enough, thanks for considering it. 

The main reason why I used your code was because of the picoprobe support. The main fork of openocd does not yet have this feature. Maybe you could make a pull request to the original codebase to merge the code for picoprobe support?

**Comment by sysprogs** [comment]
Our picoprobe support comes directly from the [Raspberry Pi OpenOCD fork](https://github.com/raspberrypi/openocd/). You should be able to build it on your side using the same steps as the regular OpenOCD.

**Comment by MKesenheimer** [comment]
Oh, wow, I didn't now that. Now I feel stupid. Thanks for the link!

**Pull request closed without merging**
