### PR TITLE
support Multi-core debugging

### PR DESCRIPTION
**Pull request by kohada-t2**
support Multi-core debugging

### CODE REVIEW

**Comment by kohada-t2** [comment]
I'm sorry. I will try again.

**Comment by sysprogs** [comment]
Sorry, we had a tight schedule this week and could not find time to review this until now. We would be happy to merge the changes if you can confirm that the script works on the hardware and provide a brief description of the board/hardware debugger you tested it with.

**Comment by kohada-t2** [comment]
This script works on:
- Renesas Salvator-X board with R-Car H3(9 cores).
- Olimex ARM-USB-TINY-H & SEGGER J-Link-OB
- Windows10 & Ubuntu1804

However...
When I recreated my branch, this pull request was closed. 
Pulled again with the recreated r-car branch.

**Comment by sysprogs** [comment]
No problem, we have merged the other request you created.

**Pull request closed without merging**
